### ISSUE TITLE
Need Right-Click to initiate a 3-way compare

### ISSUE THREAD

**Issue by That-Annoying-Guy** [WinMerge/winmerge#1044]
Currently if you select 2 files in Windows Explorer you can right-click to WinMerge and it compares the 2 files.
If you select 3 files, however, the  right-click to WinMerge is greyed out.

One of the few way to initiate a way compare is File menu -> New (3 panes)  then drag-n-drop 3 files in to WinMerge.
**Can we add a Right-Click in Windows Explorer when 3 files selected?**

**Comment by sdottaka** [comment]
In WinMerge version 2.16.x, the WinMerge context menu should be enabled when you select the three files in Explorer.

You probably have WinMerge version 2.14.0 installed on the same PC, or you may be using the old ShellExtensionU.dll.

If you don't have WinMerge version 2.14.0 installed on your PC, you should check if ShellExtensionU.dll in the WinMerge installation folder has an outdated update date.
Alternatively, try reinstalling the latest version of WinMerge and reboot your computer.

**Comment by That-Annoying-Guy** [comment]
I DID install 2.16 on top of 2.14.
I'll remove all of it and retry.
THANK YOU!!!

**Comment by That-Annoying-Guy** [comment]
New version does not remove previous version.

Removed both versions and reinstalled the latest only. (didn't even bother to reboot!)
Right-click to 3 pane compare now works.

**Comment by sdottaka** [comment]
I tried installing version 2.14.0 and then installing the latest version 2.16.16 64bit(WinMerge-2.16.16-x64-Setup.exe). I was able to reproduce that the context menu of Explorer was still set to version 2.14.0.

However, this is because Explorer has already loaded the version 2.14.0 ShellExtensionX64.dll, and restarting the computer will use the version 2.16.16 ShellExtensionX64.dll.
