### ISSUE TITLE
Source Files Comparison doesn't seem to Work properly

### ISSUE THREAD

**Issue by GCoves81** [WinMerge/winmerge#1057]
Hello,

Congratulations for this great tool!

I'm trying to compare folders of source  files (in Java but the problem appears with C++ sources as well), ignoring comments and white-spaces (they are different versions of a project, with differences among others to comments and formatting). I can't get it to work. The comparison returns "Text files are different, even for files that differ only in comments and formatting. I have set the options as described below:

Options:
- General | Whitespaces : Ignore Change
- General | Ignore blank lines: Checked
- General | Ignore comment differences: Checked
- General | Diff algorithm : default (also tried minimal and patience)
- Compare Methods: Full Contents (also tried Quick Contents)
- Plugins : Enabled (IgnoreCommentsC is Enabled too, and the "Enable automatic unpacking/prediffing for the plugin" option is checked).
- Filters : None

The problem appears in both the x86 and x64 versions.
Am I doing something wrong? Am I missing something?

I have uploaded a small test-case that reproduces the problem:
https://github.com/GCoves81/WInMergeTestCaseByGCoves81

Question:
- Is it enough to append ;\.java$ to the File Filters for the IgnoreCommentsC plugin to make it working for .java files as well? (comments syntax is the same, /* Comment */ and // Comment)

Thank you in advance.

**Comment by sdottaka** [comment]
Unfortunately, the IgnoreCommentsC plugin is a plugin that internally replaces `/* ... */` with `/**/` or `// ...` with `//`, so the comment style of the other side must be the same style.

In this case, the IgnoreCommentsC plugin replaces `/* Comment */` with `/**/`, but the other is a blank line, so it is considered different.

However, the `Ignore comment differences` option is an option to remove `/* ... */` and `// ...`, so if this option and the `Ignore blank lines` option are enabled, it must be considered identical in this case.

This issue has been fixed in commit 74e1267.

Thank you for the report.

**Comment by GCoves81** [comment]
This was an  incredibly swift response!

Many Thanks!!!
