### ISSUE TITLE
WinMerge Out Of Memory Crashes

### ISSUE THREAD

**Issue by Jayshua83** [WinMerge/winmerge#1284]
I keep getting WinMerge Out of Memory errors when comparing files. It doesn't always happen...

I have 32GB RAM. I have WAY TOO much Virtual Memory. SSDs have plenty of space!

**Comment by sdottaka** [comment]
How big are the compared files?
What kind of files are they? Is it a text file? Is it a binary file?
Are you using the 32-bit version of WinMerge? If so, there is a 2GB limit.

**Comment by Jayshua83** [comment]
Under 500MB.
Zip Files across a network.

**Comment by sdottaka** [comment]
When comparing Zip files, WinMerge's default behavior is to automatically extract the Zip file and compare the extracted folders.

Is it not behaving that way, but simply comparing them as files?

If so, have you disabled archive support in the Options dialog and then compared the ZIP files?

Do you simply want to know if there is a difference in the ZIP files? Or do you want to know in detail which parts of the ZIP file are different?

Also, when comparing large files, you should see a message box similar to the following, did you see it?
![image](https://user-images.githubusercontent.com/98126/162013921-217cae75-b1e8-49bc-b2a2-f86444346fb1.png)

**Comment by Jayshua83** [comment]
This doesn't always happen. I wish I could figure out the situation where it is... I am always comparing the same 2 folders of zip files and 90% of the  time it is fine!

**Comment by sdottaka** [comment]
I thought you were comparing large ZIP files, but you were comparing two folders with large ZIP files?

Have you specified a large value for "Threshold for switching to quick compare" or "Threshold for switching to binary compare" in the Compare/Folder category of the Options dialog? 
Also, are you comparing on a PC with a large number of CPU cores?

![image](https://user-images.githubusercontent.com/98126/162194269-24dbb558-a941-40dd-b884-5280a388c758.png)

If the above values are very large, the comparison will use a lot of memory because it will not switch from the "Full Contents" comparison method to "Binary Contents" when comparing large files.
Furthermore, if the number of CPU cores is large, comparison threads will be running for the number of CPU cores, and each thread will allocate a large amount of memory, which can easily lead to a memory shortage.

**Comment by Jayshua83** [comment]
My values above are set to default.

CPU is Quad core I think.
