### ISSUE TITLE
Winmerge help

### ISSUE THREAD

**Issue by B-Lath** [WinMerge/winmerge#1409]
Hello all,
I am having a new issue with WinMerge that I haven't experience before.  I use the program to compare CNC programs for my lathes and I noticed at the end of each line (during a compare) there is a **\par**.  Is there a way to remove that so it don't confuse people when I'm showing the difference between 2 (or 3) programs?  I've done a search for the term "par" and "\par" and nothing came up.  It seems to be a Marker, but when I delete or uncheck the box, nothing happens.  Any suggestions are appreciated. 

Bill

**Comment by sdottaka** [comment]
Your problem is that the files you are comparing does not contain "\par" but it is displayed in WinMerge? If so, could you attach the files?

If you simply want to remove "\par" for comparison, use the Replace unpacker plugin as shown below.

![image](https://user-images.githubusercontent.com/98126/179805571-6778c3f9-40dd-4645-aeb9-1bf0cb45de34.png)
![image](https://user-images.githubusercontent.com/98126/179805795-04fcb7e8-ff38-4d27-9cc4-139c2ee7beb5.png)

**Comment by B-Lath** [comment]
Thank you for the help.  I noticed that the first 2 files I compared were .rtf files and they had the \par at the end of each line.  When I saved the files as .txt and compared, the \par went away.  I will have to remember to only compare .txt files going forward.

Thank you,

Bill Latham
Manager – Engineering & Maintenance
419.634.2978
www.adatechinc.com<http://www.adatechinc.com>
