### ISSUE TITLE
Plugins are missing

### ISSUE THREAD

**Issue by diogom8** [WinMerge/winmerge#1417]
hello.

I was looking for the plugin **PrettifyJSON** but I'm unable to find it. It's mentioned in the manual https://manual.winmerge.org/en/ but it's not accessible from the plugin menu, neither I can see the dll in github.

Any clue ?

Thanks in advance for your help.

**Comment by sdottaka** [comment]
PrettifyJSON plugin is a plugin that WinMerge automatically creates in memory from the definition in MergePlugins\Plugins.xml.
For this reason, it does not exist as a DLL file.
Available since WinMerge version 2.16.13. Which version are you using?

https://github.com/WinMerge/winmerge/blob/master/Plugins/Plugins.xml#L50

**Comment by diogom8** [comment]
hello.

Updating WinMerge made the trick (I was in version 2.16.12). Sorry I haven't done it before.

thanks for your help.
