### ISSUE TITLE
Finnish translation

### ISSUE THREAD

**Issue by VeikkoM** [WinMerge/winmerge#1460]
Finnish translation for WinMerge version 2.16.22.0
[Finnish.zip](https://github.com/WinMerge/winmerge/files/9356402/Finnish.zip)

VeikkoM

**Comment by sdottaka** [comment]
Thank you for the translation.

The translation has been merged (commit 4f3f84e5a90ce5b8bcfc9aeafdfb280a9fa4083c)

I didn't apply Finnish-EXT. po in the Finnish. zip file because it didn't seem to have changed compared to the ShellExtension one.

Also, there was a large number of commented out lines in the Finnish. po file as follows :

![image](https://user-images.githubusercontent.com/98126/185192195-b6c7e2a8-751a-4b89-a01e-bc8cbe364cc3.png)

I thought it was probably not intentional, so I removed #~ and applied it.
