### ISSUE TITLE
WinMerge 3-Way Compare Bugs: Always Shows Unique Items.

### ISSUE THREAD

**Issue by WarStalkeR** [WinMerge/winmerge#154]
1) 3-Way Compare Settings (Show Left Only Different Items, Show Left Only Unique Items & Show Identical Items):
![image](https://user-images.githubusercontent.com/11169761/59681484-b9599800-91dc-11e9-8ddb-85d20f41bf9b.png)

2) Expected to behave it like it behaves in 2-Way Compare: when it shows only 1st plane different & unique items, while ignoring unique items from 2nd plane.

3) Buggy Result: 3-Way Compare shows different items from other planes even when ALL settings are disabled and it should show absolutely nothing.
![image](https://user-images.githubusercontent.com/11169761/59681855-91b6ff80-91dd-11e9-8215-afac9283cc63.png)

**Comment by sdottaka** [comment]
Thank you for the report.

I've tried to fix the bug by commit https://bitbucket.org/winmerge/winmerge/commits/77e1212d66893383d5121dcdd2914267a62168eb

Even though all settings have been disabled, some items were displayed because there were no menu items to hide the missing items only on the left[middle|right] side.

So I've added the menu items.

The latest CI artifacts are available at https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts
