### ISSUE TITLE
Release 2.16.24: One ZIP archive broken

### ISSUE THREAD

**Issue by MortenMacFly** [WinMerge/winmerge#1540]
Something is wrong with the archive of release 2.16.24:
* winmerge-2.16.24-x64-exe.zip

This files downloads with 0 or 22 Bytes. All other files work just fine.

**Comment by sdottaka** [comment]
Perhaps the zip file was flagged as unsafe by the Google safe browsing api used by the web browser, which is why the file has a size of 0 bytes.

I have already reported a False positive from the following URL I believe it is now downloading correctly, so could you please check?

https://safebrowsing.google.com/safebrowsing/report_error/

**Comment by MortenMacFly** [comment]
OK, I did that yesterday and as of today, I could download this file just fine. Thanks for the hint!
