### ISSUE TITLE
2.16.24 installer reports wrong version 2.16.22

### ISSUE THREAD

**Issue by xnoreq** [WinMerge/winmerge#1548]
Installing WinMerge-2.16.24-x64-Setup.exe results in an installer entry with version 2.16.22 instead of 2.16.24.

**Comment by sdottaka** [comment]
I am unable to reproduce this issue.

Is it possible that you used an installer with a different architecture than the previous version?
For example, you previously installed the x86 version, but this time you installed the x64 version. Or vice versa.

**Comment by o-l-a-v** [comment]
@xnoreq 

Did you use Winget? The latest manifest got the URLs for x64 vs x86 mixed up, see:

https://github.com/microsoft/winget-pkgs/blob/master/manifests/w/WinMerge/WinMerge/2.16.24.0/WinMerge.WinMerge.installer.yaml

**Comment by sdottaka** [comment]
@o-l-a-v 
Thank you for the report.
The following commit seems to have fixed this issue.
https://github.com/microsoft/winget-pkgs/pull/86984/files

@wimdelange

The WinMerge installer launches powershell to install the ShellExtension for Windows 11, but it runs powershell.exe instead of specifying an absolute path.
Therefore, the path to powershell.exe (C:\Windows\System32\WindowsPowerShell\v1.0\) must be registered in the PATH environment variable. Is the above path not registered in the PATH environment variable in your environment?

**Comment by o-l-a-v** [comment]
Maybe full path should be specified for `PowerShell.exe`? Just in case. With `sysnative` to ensure the system native version is invoked.

* `%windir%\sysnative\WindowsPowerShell\v1.0\PowerShell.exe`

**Comment by sdottaka** [comment]
@o-l-a-v 

Thank you for your suggestion. The following commit now runs powershell.exe with the full path
https://github.com/WinMerge/winmerge/commit/201827503c751c8fd67a974bea7e9840bf5438fd

**Comment by xnoreq** [comment]
@o-l-a-v Yes. After installing it with winget I uninstalled it again, and then installed it again (I think with the installer from winmerge.org), but the version still was wrong.
Today I saw that there was both an amd64 and x86 version installed, so I uninstalled both and re-installed again... Now the version number is right.

**Comment by sdottaka** [comment]
This issue is closed because it was not a WinMerge installer issue, but a WinMerge manifest file issue in winget.
