### ISSUE TITLE
Crash when copying files/folders

### ISSUE THREAD

**Issue by chylex** [WinMerge/winmerge#1558]
WinMerge started crashing maybe 75% of the times when I try to copy files/folders. I assume something is acting up in my Windows and a full system reboot would solve it, but it would be good to figure out what's going on and maybe show an error message instead of crashing.

[CrashDumps.zip](https://github.com/WinMerge/winmerge/files/9945654/CrashDumps.zip)

You can see on the video that manually copy/pasting the same files in Windows Explorer worked, but since I "upgraded" to Windows 10, sometimes the clipboard randomly stops working and copying either does nothing or shows some error message about the system not having enough resources. Maybe it's related.

https://user-images.githubusercontent.com/3685160/200166890-e6a22223-474b-4f2f-af72-7fd00507a5c4.mp4

I'm using WinMerge 2.16.24.0 (binaries-only x64), and Windows 10 21H2.

**Comment by sdottaka** [comment]
Unfortunately, I could not reproduce this crash, but I was able to identify the location of the crash with the crash dump you attached.

![image](https://user-images.githubusercontent.com/98126/200172147-c6f79b93-02f6-4822-9617-8cac52bd1235.png)

I made a fix in commit [07af303](https://github.com/WinMerge/winmerge/commit/07af3030a366332efe480f35de4c9b81ba2d2103) to prevent crashes.
(However, since I don't know what the underlying problem is, this fix may just change the crash location to another location.)

The latest CI build artifact can be downloaded from the following URL:

https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

**Comment by chylex** [comment]
Thanks for the quick response. I tried the new build and had no crashes in over 10 attempts. I also tried going back to the old build and it crashed immediately. Might just be extremely lucky/unlucky, but so far it seems it's fixed so I'm closing the issue.

I don't understand the underlying problem either. If you're bothered by weird bugs that never get explained, feel free to let me know and I'll try to step through the code in a debugger in case I find an explanation :D
