### ISSUE TITLE
Line Filters does not work

### ISSUE THREAD

**Issue by testtarou7** [WinMerge/winmerge#1620]
I am asking about the Winmerge line filter.

When comparing two text files, I want to use a line filter to exclude lines that contain certain strings from the comparison, but I can't get it to exclude them.

For example
File 1
aaa
bbb 123
ccc

File 2
aaa
bbb 456
ccc
The string "bbb" was successfully excluded for the two files.

However, even if the string "bbb" is also excluded, as shown in the image
File 1
aaa
bbb 123
ccc 123

File 2
aaa
bbb 456
ccc 456
The line filter does not work well for a series of lines with different contents.

Incidentally, in the above example, if I insert a line break (blank line) between bbb and ccc, the line filter works, but I want to apply the line filter to consecutive lines.

Please let me know if you have any solutions.
![キャプチャ](https://user-images.githubusercontent.com/121070809/208561509-698f47cb-0b85-4b66-9816-dc155f5ffa7f.JPG)

![キャプチャ2](https://user-images.githubusercontent.com/121070809/208561537-480cc7a5-0ed5-4dc3-ae90-0b04968fe611.JPG)

**Comment by sdottaka** [comment]
Unfortunately, the current line filter behaves like this.

As a workaround, instead of the line filter, if you set the PrediffLineFilter prediffer plugin as follows, I think you will get the expected result.

![image](https://user-images.githubusercontent.com/98126/208706853-18294d8b-2217-4130-ad5a-75bca587e31b.png)
![image](https://user-images.githubusercontent.com/98126/208707085-bcc0dc41-a598-490d-867b-322236599463.png)
![image](https://user-images.githubusercontent.com/98126/208707195-e924bcb5-be82-49f0-9ce2-89f5a4855838.png)

**Comment by testtarou7** [comment]
Thanks for the very clear explanation！

I got the results I expected.

I did'nt know that is the winmerge specification.

**Comment by sdottaka** [comment]
This issue will be closed with improvements in PR #2032.
