### ISSUE TITLE
Filters aren't saved anywhere

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1638]
I had to update winmerge, but i couldn't just "update" it, it wasn't working, so i had to uninstall it then install the new version.

I did saved my settings, but it didn't saved all my "filters"
strangely enough it saved the "numbers" of filter i had.

It would be better for future version if you could save it, so you could even share it for coworkers

**Comment by sdottaka** [comment]
Oh, I was able to reproduce this issue.

As a workaround, you can restore the line filters and substitution filters by performing the following steps:

1.   In the Options dialog, import the saved .ini file using the Import button and then press OK.
2.  Close WinMerge.
3.   Start WinMerge again and repeat step 1.
4.   Close WinMerge.
5.  Start WinMerge again and select the Tools -> Filters menu item.

**Comment by OshidaBCF** [comment]
i guess that on step 5 the filters will appears.


Do you have a good/easy recovery tool?
I deleted the .ini by "mistake"

**Comment by sdottaka** [comment]
> Do you have a good/easy recovery tool?

If you recently selected the [Help] → [Configuration] menu item, the configuration information will be stored at the end of C:\Users\username\OneDrive\Documents\WinMerge\WinMerge.txt, which you can save as an .ini file and import. 

This issue has been fixed in commit c7b5886. However, to restore Line filters or substitution filters, you will need to import an .ini file exported from the fixed version. 

Thank you for reporting.

**Comment by OshidaBCF** [comment]
Sadly the file is already overwritten, i cannot get the filters back
