### ISSUE TITLE
Inconsistent presentation for localization

### ISSUE THREAD

**Issue by yfdyh000** [WinMerge/winmerge#1680]
I noticed the localization of release is inconsistent with [translation files](https://github.com/WinMerge/winmerge/tree/master/Translations).
In the Simplified Chinese interface of WinMerge 2.16.24.0, the Tools - Filter menu show as "滤镜", its window title is "过滤器", and tabs is "文件筛选器", "行筛选" and "置换滤镜", they should all call "过滤器" ("filter"). The "滤镜" almost not exists in the recent translation files, the translation contains the correct translation, which seems to be modified by a certain step.

BTW, the Translators list of https://winmerge.org/translations/ is out of date.

**Comment by sdottaka** [comment]
Closing this issue as PR #1681 has been merged.

> BTW, the Translators list of https://winmerge.org/translations/ is out of date.

The page will be updated with the next release

**Comment by yfdyh000** [comment]
> Closing this issue as PR #1681 has been merged.

This PR should not solve this issue, I don't know why many "Filter" translations have been replaced in actual case.

**Comment by sdottaka** [comment]
Sorry, I seem to have misread this completely.
But I still don't understand what the problem is.

Since WinMerge 2.16.24 was released on 2022-10-27, ChineseSimplified.po has been changed in several PRs. Therefore, the translations of 2.16.24 and the current master branch are inconsistent.

WinMerge 2.16.25 Beta contains some of those changes.

https://github.com/WinMerge/winmerge/releases/download/v2.16.25/winmerge-2.16.25-x64-exe.zip

**Comment by yfdyh000** [comment]
Sorry, this issue is fixed in 2.16.25 by #1614, I missed this changes in commits.
