### ISSUE TITLE
CSV Flaws

### ISSUE THREAD

**Issue by bigboipete** [WinMerge/winmerge#1771]
WinMerge has a confusing visual approach to display a csv file/diff. There are column headers shown, that do not match with the actual field size or the file content in general.

To get a correct diff visualisation, a csv should be treated as a regular text file, which it basically is (https://datatracker.ietf.org/doc/html/rfc4180).

**Comment by sdottaka** [comment]
Is it correct that the CSV file being displayed in table format is just unexpected and that there was no specific problem?
Note that emptying CSV File Patterns in the Compare/Table category of the Options dialog will display CSV files in text format instead of table format.

![image](https://user-images.githubusercontent.com/98126/226418867-081f3fbd-af6f-4781-bf98-a33a950e4b57.png)

**Comment by sdottaka** [comment]
I will close this issue because it is possible to open the CSV file in the text comparison window instead of the table comparison window by changing the settings.
