### ISSUE TITLE
Integrate WinMerge properly into the Windows 11 File Explorer Context Menu

### ISSUE THREAD

**Issue by DavidHaslam** [WinMerge/winmerge#1836]
As it stands, after installing WinMerge in Windows 11, the only new Context Menu option is simply the program name WinMerge.

Unlike what there was in Windows 7, where the Context Menu options start with
* Select Left
* Compare

then after choosing Select Left, they change to
* Reselect Left 
* Select Middle
* Compare

Even in the extended Windows 11 Context Menu, nothing like this functionality becomes available. All it has is the program name WinMerge. 

Microsoft redesigned the File Explorer Context Menu for Windows 11, so restoring this useful functionality for WinMerge will require understanding their new requirements and implementing the necessary changes during program installation.

**Comment by sdottaka** [comment]
The menus, such as the "Select Left" menu item, appear when the "Enable advanced menu" option is enabled in the Shell Integration category of the Options dialog.
Do you have this option enabled?
By default, this option is unchecked in the installation of WinMerge for both Windows 11 and Windows 7.
![image](https://user-images.githubusercontent.com/98126/236578805-282ef2ca-7102-476e-99de-bb6425c0eff3.png)

**Comment by sdottaka** [comment]
Or, when this option is enabled, menu items such as "Select Left" are displayed as submenus of the WinMerge menu as shown below, but do you want them to be displayed in the first hierarchy?

If so, unfortunately, Windows 11 doesn't allow this to be easily achieved, probably in order to reduce the number of items displayed in the context menu.
![image](https://user-images.githubusercontent.com/98126/236582072-c1420a32-8c68-4b3b-8a1b-301688b87aa6.png)

**Comment by DavidHaslam** [comment]
Thanks! That solved my problem.

btw. It's several years since I first installed WinMerge on my old Windows 7 PC, so I may have forgotten about these were in the Options | Shell Integration settings.

NB. I already understood about the Context Menu hierarchy in Windows 11.
