### ISSUE TITLE
Silent install blocked

### ISSUE THREAD

**Issue by MrChiliCheese** [WinMerge/winmerge#1852]
Silent install is not possible, since the new DeletePreviousStartMenu function is poping up during installation.

**Comment by sdottaka** [comment]
In commit fcd9a98, Msgbox in the DeletePreviousStartMenu function was changed to SuppressibleMsgbox, so future installers can specify the /silent /suppressmsgboxes command line option to It will be possible to install without being blocked.

By the way, I think you were blocked because the message box appeared in your environment because the WinMerge start menu folder from the previous installation and the start menu folder from this installation are different. Do you have any idea what this could be?

**Comment by MrChiliCheese** [comment]
Thank you for the fix!

When installing silent the option /NOICONS is used. This results in the value `WinMerge` for the registry key `Inno Setup: Icon Group` at `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\WinMerge_is1`. If I change that to ` ` before the setup the message box is not popping up during installation.

**Comment by sdottaka** [comment]
Thank you for the info. I was able to reproduce that message box appearing with the /noicons command line option.
