### ISSUE TITLE
Spaces at the end of a line are not found.

### ISSUE THREAD

**Issue by Rollo01** [WinMerge/winmerge#2031]
Using Ver 2.16.32.0 can not find Spaces at the end of a line.

**Comment by sdottaka** [comment]
Could you please explain in more detail?
If the EOL character at the end of the line is not displayed, click View→View EOL menu item to display it.
It would be helpful if you could post a screenshot if possible.

**Comment by Rollo01** [comment]
I have 2 files that I want to compare with each other. 
![image](https://github.com/WinMerge/winmerge/assets/52415976/c416bb69-bfc5-4258-a5ce-9828c9a9fd34)
One of these files has one or two spaces at the end of a line.
![image](https://github.com/WinMerge/winmerge/assets/52415976/65819b9d-5485-400b-8a33-757e1e29f826)
These spaces are not found when I compare this file. When I copy the text to a TXT file, the space at the end of the line is recognized.
![image](https://github.com/WinMerge/winmerge/assets/52415976/bd6cf510-4211-4f6c-b950-51aba2a28c14)

**Comment by sdottaka** [comment]
Thank you for attaching the screenshot.
The screenshot shows that the two files have a different number of spaces, although the number of spaces at the end of the lines is unknown.
Are you saying the problem is that both files should have the same number of spaces at the end of the line, but WinMerge displays them differently?
Could you please attach those two files so I can check it here?

**Comment by Rollo01** [comment]
Sure here they are
[swdepot_neu.zip](https://github.com/WinMerge/winmerge/files/12593872/swdepot_neu.zip)

**Comment by sdottaka** [comment]
Thank you for attaching the file.
I still don't understand what your problem is, but when I compare your files in my environment, it shows trailing spaces and highlights the differences, similar to Notepad++.
(Note: View→View Whitespace, View→View EOL menu item are checked)

![image](https://github.com/WinMerge/winmerge/assets/98126/f4847fe9-229d-4736-ac32-f36c0d66cc71)

If your problem is that the differences are not highlighted, try selecting Whitespaces → Compare menu item as shown below.

![image](https://github.com/WinMerge/winmerge/assets/98126/3834f12c-0d6c-4aaf-ac28-2d136e50481b)

**Comment by Rollo01** [comment]
That's how it looks to me!
![image](https://github.com/WinMerge/winmerge/assets/52415976/dd9ff8c8-ed96-4f52-9bd5-ce7f10d0f466)

**Comment by sdottaka** [comment]
Am I correct in my understanding that your problem is not resolved?
The title of this issue is "Spaces at the end of a line are not found." Does this mean that WinMerge automatically removes trailing spaces?
Or do you mean not highlighting differences in the number of trailing spaces?

**Comment by Rollo01** [comment]
Sorry if I have not expressed myself correctly! My problem is not solved. In my screenshot above you can see the comparison of the two files I sent you. I also have the "Whitespaces compare" option active. But the difference is not shown (the spaces) with in the comparison of these two files, although in the one file these spaces are included. In your screenshot is also the entire text displayed with me not!

**Comment by Rollo01** [comment]
Ah one more piece of information. If I change the file extension from .dds to .txt the comparison works. So it seems that the file extension is the problem.

**Comment by sdottaka** [comment]
The file extension .dds is one of the extensions for image files.
WinMerge supports this .dds extension and will try to display it as an image.
However, since the attached files were not image files, they were not displayed correctly.
To open them as text files instead of image files, select File→Recompare As→Text menu item after opening the files. Alternatively, select Text from the menu to the right of the compare button in the Select Files or Folders window.

Alternatively, if you remove `*.dds` from Image File patterns in the Compare/Image category of the Options window, it will not be compared as an image file.

![image](https://github.com/WinMerge/winmerge/assets/98126/b5622a40-db68-4853-a6bd-63d56c9bbfaf)

**Comment by Rollo01** [comment]
Ah! Ok! thank you very much for your support. The ticket can be closed then.
