### ISSUE TITLE
Assistance with WinMerge License

### ISSUE THREAD

**Issue by nisha-9643001304** [WinMerge/winmerge#2378]
I would like to purchase a WinMerge subscription and have a few queries regarding the following areas. Could you please provide details on the points below?

1. Is it Opensource / Licensed?
2. License Type (Enterprise, per user, etc.)
3. Multi-device Licensing Data Storage (license linked, device linked, etc.) 
4. OS Language Adaptation 
5. Test License Required Source
6. OS Language Adaptation Source

Thank you!
Nisha

**Comment by sdottaka** [comment]
1. Is it Open Source / Licensed?
WinMerge is an open-source software.

2. License Type (Enterprise, per user, etc.)
WinMerge is released under the GNU General Public License version 2 (GPLv2). This means it is freely available for both personal and commercial use, and you can modify and distribute the software under the same license terms.

3. Multi-device Licensing Data Storage (license linked, device linked, etc.)
Since WinMerge is open-source software under the GPLv2, there is no licensing fee, and the license is not linked to specific devices or users. You can install and use it on multiple devices without any restrictions.

4. OS Language Adaptation
WinMerge supports multiple languages and can adapt to the operating system's language settings. Currently, it supports 37 languages. You can select your preferred language from the application's settings.

5. Test License Required Source
There is no need for a test license for WinMerge, as it is freely available under the GPLv2 license. You can download, install, and use the software without any cost or licensing requirements.

6. OS Language Adaptation Source
The source code of WinMerge includes support for multiple languages. You can download the source code and localization files from the official WinMerge repository on GitHub: [WinMerge GitHub Repository](https://github.com/WinMerge/winmerge). Additionally, the translation status for each supported language can be checked at the following URL: [WinMerge Translations](https://winmerge.org/translations/?lang=en).

**Comment by nisha-9643001304** [comment]
Hi  Takashi and Team,

Thank you for reaching out to me.

Could you please confirm a few more queries.

1.  Can we use one license on multiple devices simultaneously?
2.  Is the application data  license linked / device linked? If the user
logs in from a different device will the data get wiped out from the old
device?
3.  User is moving from one device to another device, in that case will he
need the new licenses? Or will his old license work?

Thanks,
Nisha

**Comment by sdottaka** [comment]
> 1. Can we use one license on multiple devices simultaneously?

Yes, you can use WinMerge on multiple devices simultaneously. WinMerge is open-source software released under the GNU General Public License version 2 (GPLv2), so there is no licensing fee and no restrictions on the number of devices.

>2. Is the application data license linked / device linked? If the user logs in from a different device will the data get wiped out from the old device?

WinMerge itself does not manage or store user data in a way that is linked to a license or device. It is a file comparison tool that operates on the files present on your system. Therefore, switching devices does not affect the data or settings of WinMerge.

> 3. User is moving from one device to another device, in that case will he need new licenses? Or will his old license work?

Since WinMerge is open-source software under the GPLv2 license, there is no need for new licenses when moving from one device to another. You can freely install and use WinMerge on the new device without any licensing issues.
