### ISSUE TITLE
Wrong syntax highlighting for TeX files

### ISSUE THREAD

**Issue by lmendo** [WinMerge/winmerge#2415]
The syntax highlighting for TeX files seems to be incorrect. It marks certain words as TeX/LaTeX commands, when they are not. See for example the words "large" and "in" on the first line of the image.

![image](https://github.com/user-attachments/assets/58ce707c-b2c6-4a3f-aee2-4f7a18f350a8)

**Comment by sdottaka** [comment]
Thank you for reporting this issue. It has been resolved in https://github.com/WinMerge/winmerge/commit/2d40a9837b1be807f5b870c8e7264d0455ec128d

**Comment by lmendo** [comment]
Thank you for resolving this. Do you have an idea when this fix will be incorporated into a version I can install? The current version shown on the web page is still 2.16.42.1 from 2024-07-28

**Comment by sdottaka** [comment]
The next stable version, 2.16.44, is scheduled to be released on 10/27, but it may be delayed a little due to troubles with updating the code signing certificate.

The CI build artifact is available from the following URL:

https://ci.appveyor.com/project/sdottaka/winmerge/builds/50698596/artifacts

or

https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

**Comment by lmendo** [comment]
Thank you!
