### ISSUE TITLE
Option to automatically unzip archives

### ISSUE THREAD

**Issue by SIS-JoshTS** [WinMerge/winmerge#2427]
Hey folks! It would be nice if there was an option to automatically unzip archives when doing a folder compare. This could manifest in one of two ways:
- (Preferred) They are extracted and shown as folders, allowing their contents to be diffed directly in the root folder compare
- Zip files are automatically opened as if they were double clicked (opening a new tab per zip file)

If this functionality already exists, please let me know. I've been trying to find a good solution for this for quite some time.

Cheers

**Comment by sdottaka** [comment]
When you specify ZIP files to compare, WinMerge automatically compares them as folders, but does this mean that the comparison doesn't work properly in your environment?

Or do you mean that when comparing normal folders, you want to compare the ZIP files in those folders so that they appear as folders, rather than as files?

WinMerge can't do the latter.

![image](https://github.com/user-attachments/assets/18b156bb-8f29-48a4-b404-61723b3ab14b)
![image](https://github.com/user-attachments/assets/a638cce4-3c2b-4477-af84-d47ba0c9a51b)

**Comment by SIS-JoshTS** [comment]
I was hoping for the latter, as is suggested by #2432. I'll close this one as the other one is exactly what I'm looking for.
