### ISSUE TITLE
One suggestion: You should save the settings in an "ini" file instead of in the registry, especially the zip version.. 

### ISSUE THREAD

**Issue by 265785** [WinMerge/winmerge#248]
The portable versions of WinMerge is not portable anymore.
When I download the portable versions (Zip version) of WinMerge on your website, and I place it on my portable drive, I found that WinMerge saved the settings and so on in the registry. And the settings is unabie to delete if I don't browse the registry by myself. 
![搜狗截图20200104162155](https://user-images.githubusercontent.com/56037874/71762747-60e6af80-2f0e-11ea-8ad0-e291029c77e5.png)
![搜狗截图20191203010241](https://user-images.githubusercontent.com/56037874/71762702-bff7f480-2f0d-11ea-9036-78517ce07d98.png)
So the settings in the registry becomes rubbish when I delete the portable version of WinMerge. and it is hard to delete, Only if I browse the registry or reinstall the system. 
Also,I found that WinMerge is impossible to place in a portable drive. If I place the WinMerge in a portable drive, the settings is unable to save in the portable drive. If I change the computer, the settings will be lost, and it produces rubbish in the previous computer's registry. I have to make setting backups and I have to import the settings each time I change one computer. that's too much trouble. 
In order to solve this problem, I can give you one suggesstion: 
You should save the settings in an "ini" file instead of in the registry. and the "ini" file can be placed in the root folder of your program. Also your software should directly read the settings in the "ini" file directly instead of reading the registy. 
Like this (XnView): 
![搜狗截图20200104160500](https://user-images.githubusercontent.com/56037874/71762712-daca6900-2f0d-11ea-9690-6ea3aea07696.png)
And this (Everything): 
![搜狗截图20200104160749](https://user-images.githubusercontent.com/56037874/71762716-fa619180-2f0d-11ea-8d31-ff8c2baa7177.png)
This can not only make your software portable, but also make the settings backuping much more easily. 
I hope you can receive my suggestions. Thank you!

**Comment by MailYouLater** [comment]
Note: Saving settings in the registry is fine for a normal install, but there are people who prefer portability, so it would be very nice if there was an option to save the settings to an ini instead.
WinMerge Portable has a workaround for this issue in that it has a launcher which loads the settings into the registry, launches WinMerge, waits for WinMerge to exit, then moves the settings back to disk, but it would be much nicer if it didn't have to have a launcher which waits around to clean up after it.

My recommendation for how to implement this to be as useful as possible for as many people as possible would be to have WinMerge look for a settings file with a predetermined name in the same folder as the exe file (e.g. `settings.ini`), then if that doesn't exist fall back to using the registry just like it does today, and to also have a command line argument which can override the normal location of the settings file and force WinMerge to use a specified file as its settings file (e.g. `/settings=..\..\Data\settings.ini`).

It would also be really nice if specifying a settings file that doesn't exist yet on the command line would load the settings from the registry, but save the settings to the specified settings file.  That would make migrating your existing settings from the registry to a settings file much easier.  (Removing the settings from the registry after such a migration can be left to the user, as some users may still want to keep them there too, for example if they just want to copy the settings from their main computer to a copy they have on a USB flash drive.)

**Comment by grzesie** [comment]
Is someone working on it? If not i would like to try make this change.

**Comment by sdottaka** [comment]
Implemented in PR #750

**Comment by MailYouLater** [comment]
From a quick glance through the code added in that PR plus a couple of the later related commits... this is looking very promising.  I look forward to testing this out soon.

**Comment by MailYouLater** [comment]
Hmm... I downloaded a CI build and if I place a blank file named `winmerge.ini` in WinMerge's program directory, it seems to work as expected, however, if I use the `/inifile <filename>` parameter to point it to another file, it doesn't seem to work as expected.

**Comment by MailYouLater** [comment]
Oh... I see, if I point it to another filename without specifying a directory (e.g. `WinMergeU.exe /inifile test.ini`), it fails to load the settings from either the ini file or the registry, and doesn't save the changes to either either... it also doesn't output any errors... however, if I include a path to the ini file (either absolute, e.g. `C:\Path\to\winmerge\test.ini` or relative, e.g. `.\test.ini`) it seems to work as expected... that's not a big issue for me, but could definitely be a source of confusion if it doesn't get fixed.

@sdottaka&#8288;/@grzesie Should I open a new issue for this? or is that unnecessary because this feature (which isn't in a stable build yet) is being tracked in this issue?

**Comment by sdottaka** [comment]
@MailYouLater
The problem has been fixed in commit 010a140
Thank you for the report.

**Comment by MailYouLater** [comment]
@sdottaka: Thanks.  That commit fixed that issue perfectly.  I did a few more tests with an ini file, and I see that if the registry has no existing WinMerge references, when launching WinMerge such that it uses an ini file (whether by inserting a `winmerge.ini` file in the appropriate location, or by specifying an `/inifile` command line argument) the following still ends up in the registry:

    [HKEY_CURRENT_USER\SOFTWARE\Thingamahoochie\WinMerge]
    "Executable"="C:\\Path\\to\\WinMerge\\WinMergeU.exe"
    "ContextMenuEnabled"=dword:00000000

Sorry I didn't catch this in my previous testing, and thank you so much for continuing to support WinMerge.

**Comment by sdottaka** [comment]
Thank you for testing.

The above registry keys are not settings for WinMerge itself, but for shell extension and external applications, so the value is intentionally stored in the registry.

**Comment by MailYouLater** [comment]
Hmmm... That's disappointing.  The intent of requesting the ability to use an INI file instead of the registry was basically to isolate a 'portable' instance of WinMerge (e.g. running from a USB flash drive) from the registry so that it a) won't leave unnecessary traces behind in the registry, and b) if there's a local install, it doesn't alter anything from/for the local instance.

I was hoping that using the INI file to save the options would mean that there would no longer be any need for WinMergePortable to keep the launcher running in the background waiting to clean up after a portable instance of WinMerge, and it's _so_ close, but unfortunately, as it is right now, the launcher will still have to wait and clean up after it.

Well, thank you guys so much for your work on this so far, and I guess, if those are 'not settings for WinMerge itself', then I should open a separate issue to discuss what's necessary to have a portable edition of WinMerge not use them, or not leave them behind...

**Comment by Tback1** [comment]
@MailYouLater @SamuelPlentz 
Even if the/ini parameter is used, booting from ContextMenu does not use the settings of the ini file, but rather writes a large number of parameters in the registry. 

It is recommended to consider placing a protable file without a suffix in the winmerge folder. You can write a redirect field inside to customize the location of the ini file. 

When starting, if a protable file is found in the root directory, it is not read or written to the registry. Instead, it searches for the ini file based on the redirect field
