### ISSUE TITLE
Installer - Run PowerShell hidden and with `-NoProfile` when installing silently

### ISSUE THREAD

**Issue by o-l-a-v** [WinMerge/winmerge#2515]
## Context

Following command:

```cmd
winget install --silent --id WinMerge.WinMerge --scope user
```

Downloads and installs <https://github.com/WinMerge/winmerge/releases/download/v2.16.44/WinMerge-2.16.44-x64-PerUser-Setup.exe> with `/SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART`.

In the middle of the installation a visible PowerShell window pops up, and it is loading the PowerShell profile before installing.

## Feature requests

1. Run PowerShell hidden from the installer with something like `PowerShell.exe -WindowStyle hidden`
2. Don't load the PowerShell profile, use `PowerShell.exe -NoProfile`.

Example command I've successfully used from Intune when running PowerShell scripts in user context in the past:

```powershell
"%SystemRoot%\sysnative\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy "Bypass" `
    -NoLogo -NonInteractive -NoProfile -WindowStyle "Hidden" `
    -Command "& '.\User_Install-ClientTroubleshootingTools.ps1'; exit $LASTEXITCODE"
```

## Workaround

Use [Scoop](https://scoop.sh/): `scoop install extras/winmerge`.

**Comment by sdottaka** [comment]
Sorry for the late response.

1. Is there any reason to hide the Powershell window other than it looks bad? (I want to keep the Powershell window because it shows the progress of the shell extension installation.)

2. Am I correct in understanding that adding the -NoProfile command line option can avoid environment-dependent issues?

**Comment by o-l-a-v** [comment]
1. I think the most common understanding of what quiet / silent actually implies is to show nothing. That's also what the Inno Setup switched passed by WinGet (`/VERYSILENT`) implies (link below). If you want progress to be shown, don't pass `/VERYSILENT`, but `/SILENT`.
   * <https://jrsoftware.org/ishelp/index.php?topic=setupcmdline>
1. Yes, correct. You'll run "vanilla" PowerShell that way.
   * <https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles>
   * <https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh?view=powershell-7.4#-noprofile---nop>

**Comment by sdottaka** [comment]
The `-NoProfile -WindowStyle "Hidden"` command line options have been added in commit https://github.com/WinMerge/winmerge/commit/2537e216d456d6bfe8b7fe7c049200d9bde448cf.
However, due to the following issue, the window appears for just a moment. We welcome PRs on this issue.
https://github.com/PowerShell/PowerShell/issues/3028
