### ISSUE TITLE
Option Suggestion

### ISSUE THREAD

**Issue by dtoxic47** [WinMerge/winmerge#2555]
There should be a option to clear the recently opened folders  in the choose folders dialog.

Either a button to manually clear recent folders history or a option to clear history on exit

**Comment by sdottaka** [comment]
When you press the "Clear all recent items" button in the Shell Integration category of the Options dialog, the recent items displayed in the File → Recent Files Or Folders menu are deleted.

However, the history displayed in the lists of each combo box in the "Select Files or Folders" window was not deleted.

For this reason, a fix was made in commit 85b763341671fc235412cbdfc965be3fb6ceffd6 so that the history displayed in the lists of each combo box in the "Select Files or Folders" window is also deleted.

![image](https://github.com/user-attachments/assets/86aecd8f-9b2b-4acf-9f80-ea4504b18126)
