### ISSUE TITLE
[Spanish translation] Some texts of the "find dialog" are not translated

### ISSUE THREAD

**Issue by borjafg** [WinMerge/winmerge#261]
![Screenshot](https://user-images.githubusercontent.com/6740268/73723595-affc4c00-4729-11ea-9964-f859f415e9cc.png)

**Comment by sdottaka** [comment]
This is not a bug. Simply, there is no Spanish translation in Spanish.po file as follows:

https://github.com/WinMerge/winmerge/blob/master/Translations/WinMerge/Spanish.po#L1359
https://github.com/WinMerge/winmerge/blob/master/Translations/WinMerge/Spanish.po#L1320

Pull Requests are welcome.

**Comment by MailYouLater** [comment]
@borjafg: As you can see in [this table](https://winmerge.org/translations/#winmerge), the Spanish translation hasn't been updated in quite a while and is missing a number of translations.  If you would like to help update the Spanish translation, there are instructions on how to do so at https://winmerge.org/translations/instructions.php though these instructions are a bit out of date, so you'll likely want to start by forking and cloning this repository, then follow the "Update existing language" section of "The Recommended Way" listed in the [WinMerge Translation instructions](https://winmerge.org/translateions/instructions.php) and when you get to the point where it says you should upload a patch to SF.net, you should instead commit and push your changes and submit them as a pull request as sdottaka suggested in his previous comment.

If you're not familiar with how to fork and clone a git repository and/or how to submit your changes as a pull request, I found a decent walkthrough at https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/ that you can follow.

**Comment by borjafg** [comment]
Why are there ampersands (&) in the texts?


![image](https://user-images.githubusercontent.com/6740268/74563734-b7afc200-4f6d-11ea-9b38-eac1c26d69e9.png)

**Comment by MailYouLater** [comment]
This marks the keyboard accessibility shortcut for an interactive button or menu item.  Windows displays these accessibility shortcuts by underlining the letter after the `&`, and the user can choose to press that keyboard button (or hold <kbd>Alt</kbd> and press it if currently in a text input) instead of using the mouse.

For instance, `&Find Next` and `Find &Prev` are used to define the text on the "Find Next" and "Find Prev" buttons in the screenshot below, and if you press <kbd>Alt</kbd>+<kbd>F</kbd> or <kbd>Alt</kbd>+<kbd>P</kbd> (Alt key only being required if the text input is focused) it will find the next or previous instance of your search string respectively just as if you'd clicked the corresponding button with the mouse.
![image](https://user-images.githubusercontent.com/1279475/74565532-3ed94780-4f26-11ea-9c99-6409580754a8.png)
