### ISSUE TITLE
The icons on a 43" 4K screen are too small.

### ISSUE THREAD

**Issue by MichaelIsGreat123** [WinMerge/winmerge#276]
Thanks for sharing WinMerge. 

---
![WinMerge - on a 43 inch 4K monitor, the icons that are just below the Menu options (File, Edit, View, and so on) are simply way too small](https://user-images.githubusercontent.com/50324124/75648765-fb324d80-5c48-11ea-98ad-4616f27bcf82.jpg)
Suggestion for an indispensable improvement:
On a 43" 4K screen, the icons that are just below the Menu options (File, Edit, View, and so on) are simply way too small. If you could add the feature to support 43" 4K screen on Windows 10, it would be really great with putting icons that are of a much bigger size than the ones currently available. Thanks.

**Comment by MailYouLater** [comment]
The size of the screen has nothing to do with this, the icons are also too small on a smaller 4K screen.  The issue is lack of support for scaling on High-DPI screens.

Windows has an option to scale such elements when connected to High-DPI monitors.
![image](https://user-images.githubusercontent.com/1279475/75708189-36e30c80-5c75-11ea-963f-0473353bbb54.png)
WinMerge doesn't (yet) support scaling in response to this setting.

**Comment by sdottaka** [comment]
Currently, WinMerge menu item icons do not support High-DPI.
However, toolbar icons can be resized with View-> Toolbar menu item.

**Comment by MarcAnt01** [comment]
In my 3000x2000 13 .5 inches display with 250% scaling it's even more evident, having DPI awareness would be great even if I can work around that through the option
