### ISSUE TITLE
Subfolder context menu -> Compare destroys existing results

### ISSUE THREAD

**Issue by NeatNit** [WinMerge/winmerge#277]
I just used WinMerge for the first time today, comparing two big-ish folders including sub-folders.

At some point I right-clicked one of the sub-folders and clicked Compare (I might want to do this to, for example, change view settings which would only make sense for that particular sub-folder). WinMerge then compared them *in the same tab*, making it impossible to go back to the original comparison. I couldn't find a Back button or an Up button, so I must assume the results of the previous comparison were lost (perhaps not even in memory anymore), and I had to run the whole diff again.

So either there's a missing "Back" button, or the "Compare" context menu option should open in a new tab rather than the same one.

**Comment by MailYouLater** [comment]
I agree.  I think the new compare should open in a new tab.

**Comment by sdottaka** [comment]
Hold down the Ctrl key and click the Compare menu item to display the results of the folder comparison in a new window.

I'm thinking about whether this should be the default and whether it can be set as an option.

**Comment by NeatNit** [comment]
Is that even discoverable at all?

**Comment by MailYouLater** [comment]
I should have tried that.  That's great.  I personally prefer this type of keyboard shortcut for such options, but as @NeatNit says, it sure would have been nice if it was more discoverable, I've been dealing with it not working the way I wanted for ages and never thought to try Ctrl+clicking.  Also, an option to switch which is the default would be nice too. (I rarely want to open in same window, but it would be handy occasionally.)

I can see it being made more discoverable by editing the text to include a mention of it, but I'm not sure how it should be done without messing up the visuals of the context menu.  Another option if you add a setting in the Options dialog which allows you to switch the default would be to mention that holding Ctrl while clicking Compare will switch to the other option.

Another option which would be awesome to have would be to add a Shift+Click to open the new compare in a separate WinMerge window.  I doubt anyone would ever want it as their default, but I have had times when it would have come in very handy.

**Comment by snarkywolverine** [comment]
I just hit this issue and came here to complain about this.  If you're not going to make the new tab the default (which IMO you should), the menu item should at least be changed to say:

Compare (Ctrl-Click to open in a new tab)

Or, you should have a separate option to open in a new tab.

That way, I at least get warning that I'm about to overwrite/lose my existing context (with no recovery).

I just lost 5 hours worth of comparison data because of this (~80k files).

**Comment by tfbroner** [comment]
I think this is a bug actually. The design of the application is MDI/Tabbed, therefore any action that would result in the current tab being destroyed should open in a new Tab. This could be configurable, but the fact that it does destroy the current comparison results, is a bug I believe. 
Another reason for it being a bug, is the fact that it should at least follow the Single instance mode configuration. If the Single instance is disabled, everytime I do Compare from Shell, I will get a new Comparison tab in a new window, if it's enabled, it's a new Tab.
Compare from context menu should follow exactly the same principle.

**Comment by MailYouLater** [comment]
> I think this is a bug actually.

There's no spec or documenation anywhere stating that this is _supposed_ to open in a new tab, and while replacing the current comparison by default may seem like a poor choice, the fact that the option to open the new comparison in a separate tab via a <kbd>Ctrl</kbd>+Click has been added proves that it's not an unintended behavior, or the dev would have changed the behavior instead of adding another option.  So no.  It's not a bug.

On the other hand, it is not entirely intuitive, does not warn the user that they will lose their current comparison, and the option to open the new comparison in a separate tab is not obvious.  Perhaps we could at least get a warning that tells the user what to expect, and how to use the optional <kbd>Ctrl</kbd>+Click behavior the first time they click it.

**Comment by NeatNit** [comment]
Whatever you want to call it, I think we're all in agreement that the current state is bad.

The default behaviour should be changed to compare in a new tab. Virtually no user would expect their work to be lost when clicking this option.

What the developer thought at the time is irrelevant. WinMerge is a tool, and it should strive not to cause lost work or pains whenever possible. Here is a case where it fails at this.

I don't care if there is or isn't an option to use the same tab instead. But at this point it seems like the best option is to remove such an option, because:
- You can't use ctrl+click to open in the same tab, this will harm those who are used to the exact opposite behaviour in the current version
- You *can* if you add a warning, but that would just add clutter to the brain and complicate code (probably)
- Either way, it's again not discoverable (although in this case there's very little merit to it anyway so it doesn't matter)
- You can use a different modifier key (e.g. Alt or Shift) but that would probably be inconsistent with a lot of other things in WinMerge

All in all, it's best off to leave that functionality out IMO. Just make it always open in a new tab.

@sdottaka any chance you'll take a look at this again? It should be a 5 minute fix and can save hundreds of hours of work.

**Comment by sdottaka** [comment]
If the Include Subfolder checkbox is checked and Tree mode is enabled, I agree with the idea that subfolders should be compared in a separate tab.

However, when the Include Subfolders checkbox is unchecked, I want the subfolders to be compared in the same tab. This is because I want WinMerge to behave like Explorer.

My idea now is ...

- If the Include Subfolder checkbox is checked, remove the "Compare" menu item from the Context menu and add a "Compare in new window" menu item.

- If the Include Subfolder checkbox is checked, add the Compare menu item and the Compare in new window menu item to the Context menu.

- If it's easy to implement, I'd like to see a warning message box when I select the "Compare" menu item if the folder comparison time was 10 seconds or more.

**Comment by NeatNit** [comment]
Sounds like a good plan.

On another note, if you want WinMerge to behave like Explorer, add a Back button. Make sure it caches the results of older comparisons.

(Disclaimer: I actually haven't used WinMerge much recently, just still getting email updates for this issue. I don't know if there already is a back button)

**Comment by MailYouLater** [comment]
No, there's no back button, and this would only be useful in a few configurations.  IDK how much others would use it, but I think caching the previous results to have a decent back button experience would likely be nontrivial, and such suggestions should be discussed in a separate issue.

Personally, I think making this behave differently based on if view subfolders and/or tree view are checked is unnecessary complication, and a message box that asks the user to verify that they want to replace their current comparison, informs them of the <kbd>Ctrl</kbd>+Click functionality, and (like many of WinMerge's message boxes) has a 'Don't show this again' checkbox would be good.

Also, if you do change the default behavior to open in a new tab in some situations, it would be nice to have the ability to choose to do the comparison in the current tab when desired, e.g. by <kbd>Alt</kbd>+Clicking.

**Comment by tfbroner** [comment]
I think there are no drawbacks to making it open in a new tab, nothing will really change, except for the new tab, and the existing workflows will still work as before. ESC to close window doesn't affect it either. 
I think the easiest way forward is to make it open in new tab always, no matter if Ctrl is pressed or not - minimum changes, and no new entries in the menus or changes to existing ones; no message boxes or anything else.

**Comment by sdottaka** [comment]
In version 2.16.14, "Compare in new window" has been added to the context menu.

![image](https://user-images.githubusercontent.com/98126/133914549-a5a24858-8f15-4288-b5d7-9f713c98dcb3.png)
