### ISSUE TITLE
Real Differences are ignored when comparing Unix to Windows files

### ISSUE THREAD

**Issue by TimSmith** [WinMerge/winmerge#286]
If Ignore carriage return differences (Windows/Unix/Mac) is enabled then all differences are being ignored not just line termination ones.

version: 2.16.6 and 2.16.2

[compare_files.zip](https://github.com/WinMerge/winmerge/files/4349294/compare_files.zip)
[WinMerge.txt](https://github.com/WinMerge/winmerge/files/4349299/WinMerge.txt)

**Comment by sdottaka** [comment]
Since you have enabled the "Automatic Prediffer" menu item in the "Plugins" menu, the IgnoreCommentsC.dll Prediffer Plugin has been applied and the differences in comments have been ignored.

However, it is a bug that is displayed as follows, so it has been fixed in 0a10ed240a8fd533806e2068111eda29ee4a2dc6.

![image](https://user-images.githubusercontent.com/98126/77226739-f9133d00-6bbd-11ea-8775-4a14104d055c.png)

↓

![image](https://user-images.githubusercontent.com/98126/77226756-16e0a200-6bbe-11ea-92fc-837dda953556.png)
