### ISSUE TITLE
Normal x64 installer is missing for 2.16.6

### ISSUE THREAD

**Issue by Neustradamus** [WinMerge/winmerge#350]
2.16.4:
- winmerge-2.16.4-full-src.7z
- winmerge-2.16.4-exe.zip
- winmerge-2.16.4-x64-exe.zip
- WinMerge-2.16.4-Setup.exe
- WinMerge-2.16.4-x64-Setup.exe
- readme.txt

2.16.6:
- WinMerge-2.16.6-x64-Setup_no_support_for_per-user_installation.exe
- winmerge-2.16.6-exe.zip
- winmerge-2.16.6-x64-exe.zip
- winmerge-2.16.6-full-src.7z
- WinMerge-2.16.6-Setup.exe
- readme.txt

**Comment by sdottaka** [comment]
The 2.16.6 x64 installer was created with InnoSetup 6.0.x to support per-user installation and was going to be released. However, when I checked the created installer at virustotal.com, multiple virus scan engines determined that it was malware and could not be released.

For this reason, I created WinMerge-2.16.6-x64-Setup_no_support_for_per-user_installation.exe with InSetup 5.x instead.

If the situation does not improve in the next version, the installer created with InnoSetup 5.x will be released as WinMerge-2.16.8-Setup.exe.

**Comment by sdottaka** [comment]
Unfortunately, the situation hasn't changed, so I'll use InnoSetup 5.x for version 2.16.8 as well.

Since the installer created by InnoSetup 5.x cannot select per-user install and normal install, I will add an installer for per-user installation as follows.

2.16.6:
- WinMerge-2.16.8-x64-Setup.exe
- WinMerge-2.16.8-x64-PerUser-Setup.exe
- WinMerge-2.16.6-Setup.exe
- winmerge-2.16.6-x64-exe.zip
- winmerge-2.16.6-exe.zip
- winmerge-2.16.6-full-src.7z
- readme.txt
