### ISSUE TITLE
Windows XP x64 Edition

### ISSUE THREAD

**Issue by DotNetTester** [WinMerge/winmerge#378]
The 64-bit build of WinMerge 2.16.2 works fine but the 64-bit builds of WinMerge 2.16.4 and 2.16.6 are broken on Windows XP x64 Edition.

**Comment by sdottaka** [comment]
I have built WinMerge 64bit version from a certain version with Visual Studio 2019, so it only works on Windows 7 or later. In order to support XP, the WinMerge 32bit version is built with Visual Studio 2017.

Therefore, please use the 32-bit version for XP 64-bit OS.
This seems to need to be documented somewhere.

**Comment by sdottaka** [comment]
Commit 2538901 and https://github.com/WinMerge/website/pull/4/commits/17ac3db283687d3ca2c4c3762e5dc5e4330edf65 state that 64-bit version requires Windows 7 or later
