### ISSUE TITLE
Commandline to display versions in the output report

### ISSUE THREAD

**Issue by arunjayaraj1988** [WinMerge/winmerge#418]
Please add an option to display Left File Version and Right File Version in the report when the report is generated through the command line. 

Below line generate the report. but doesn't displays the dll version in the report. 
Start-Process -FilePath $winMergeExePath -ArgumentList "$fullUNCLeftPath $fullUNCRightPath  -minimize -noninteractive -noprefs -cfg Settings/DirViewExpandSubdirs=1 -cfg ReportFiles/ReportType=2 -cfg ReportFiles/IncludeFileCmpReport=1 -r -or $reportPath" -wait

**Comment by sdottaka** [comment]
Fixed by commit 780be6d

For latest CI builds, you can add the following option to add the version column:

`-cfg "DirView/ColumnOrders=0 1 2 3 4 -1 -1 5 -1 -1 -1 -1 -1 6 7 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1"`

[CI build artifact]
https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts
or
https://github.com/WinMerge/winmerge/actions/runs/231280345

For the value to be set in the above option, specify the same value as the value of the following registry key after adding the column with WinMerge once.

`HKEY_CURRENT_USER\SOFTWARE\Thingamahoochie\WinMerge\DirView\ColumnOrders`

**Comment by arunjayaraj1988** [comment]
Will this be included in the next release?

**Comment by sdottaka** [comment]
Yes. The fix will be included in the next release.

**Comment by arunjayaraj1988** [comment]
Any tentative date on the release?

**Comment by sdottaka** [comment]
I want to release a new version every 3 or 4 months, but I don't have a specific date.
