### ISSUE TITLE
Compare two .xls file

### ISSUE THREAD

**Issue by JackKumar33** [WinMerge/winmerge#540]
While try to compare two excel(.xls) file I am getting the below mentioned error.
![Screenshot_986](https://user-images.githubusercontent.com/75119289/103760710-7fa8e600-503b-11eb-8064-7b863b2f22d0.png)

**Comment by sdottaka** [comment]
Probably because you don't have Excel installed on your PC, you're getting an error with a plugin that uses Excel.

If you want to compare .xls files without using Excel, you can use the xdocdiff WinMerge plugin (http://freemind.s57.xrea.com/xdocdiffPlugin/en/index.html ) or the Diff tool that can compare Excel files. (ex. https://github.com/skanmera/ExcelMerge/)

**Comment by datadiode** [comment]
https://github.com/datadiode/winmerge2011 supports .xls(x) file comparison through ReoGrid and b2xtranslator.
