### ISSUE TITLE
Installer issue with Polish diacratics characters

### ISSUE THREAD

**Issue by mlipok** [WinMerge/winmerge#589]
![image](https://user-images.githubusercontent.com/11089482/106384419-064aac00-63cb-11eb-96ee-eaabd63b0eb6.png)

![image](https://user-images.githubusercontent.com/11089482/106384369-d3a0b380-63ca-11eb-94c0-77af015ce5ae.png)

How I can help in fixing this issue ?

EDIT: btw. there are also other strings to fix.

**Comment by sdottaka** [comment]
Fixed by commit 1705842

Could you please check if the garbled characters have been fixed with the latest installer below? 

https://ci.appveyor.com/project/sdottaka/winmerge/builds/37534089/artifacts

![image](https://user-images.githubusercontent.com/98126/106385237-9102c980-6412-11eb-9eab-0ba7fb35ed47.png)
![image](https://user-images.githubusercontent.com/98126/106385258-b8f22d00-6412-11eb-9223-263233d8578b.png)
![image](https://user-images.githubusercontent.com/98126/106385264-c4ddef00-6412-11eb-9144-8093c76cf190.png)

**Comment by mlipok** [comment]
Confirmed that this fix fixes the issue.

**Comment by sdottaka** [comment]
Thank you for your confirmation.
