### ISSUE TITLE
Command-line output the merge document not working

### ISSUE THREAD

**Issue by pcakhilnadh** [WinMerge/winmerge#732]
Hi There,

I tried `-o` parameter as mentioned in the [documentation](https://manual.winmerge.org/en/Command_line.html). But it doesn't give me any response. I didn't understand what I might be doing wrong.

`WinMergeU file1\t1.pdf file2\t1.pdf -o D:/`

Also, is it possible to get the comparison result by line number and position?

**Comment by Pierre-de-la-Verre** [comment]
I can't find -o in the documentation, only /o.
And have you tired with simple text files? PDF is maybe more complicated to handle ..

**Comment by pcakhilnadh** [comment]
@Pierre-de-la-Verre , In that documentation it is written that `-o` and `/o` are same. In fact I have tried with /o also. 
No, I was checking with pdf files only . I have used xdocdif plugin . I will check on text file and update

**Comment by sdottaka** [comment]
Sorry for the late reply.

The description of the /o command line option was wrong, it is the file path that is specified, not the folder path.

This description has been fixed in commit eb49e7c, 1cf6831.

Note that the xdocdiff plugin does not have the ability to write back to PDF files, so it is not possible to reflect the merged/edited files to the PDF files.
