### ISSUE TITLE
Unable to modify WinMerge.txt

### ISSUE THREAD

**Issue by maettu-this** [WinMerge/winmerge#785]
`Hilfe > Konfiguration` (presumably `Help > Configuration`) results in:
```
Kann Datei nicht öffnen
\\<server>\homedrive$\<user>\Documents\WinMerge\WinMerge.txt

Path not found: \\<server>\homedrive$\<user>\Documents\WinMerge\WinMerge.txt
```

The issue may be related to the fact, that the users home directory is mapped to `\\<server>\homedrive$\<user>` by the companies IT. The issue may also be caused due to the big upgrade step from an old 2013 version to the latest one.

I found the issue when trying to change from German to English. I searched the registry for some link to "WinMerge.txt" but couldn't find anything else than shell/plugin/extension/integration stuff.

**Comment by sdottaka** [comment]
The output folder of WinMerge.txt is fixed to {My Documents folder}\WinMerge.

If the above folder doesn't exist, WinMerge will try to create it, but I think it failed because you don't have permission. Or maybe WinMerge.txt is read-only.

Is it possible to create the above folder manually?

I've fixed it with commit d5abe5c to create WinMerge.txt in a temporary folder if the file creation failed.

**Comment by maettu-this** [comment]
The folder did not exist at all. But I could manually create it. Now `Help > Configuration` works and editing `WinMerge.txt` as well.

So access to folder and file is not restricted for my user. Seems as if WinMerge did not properly inherit my access permissions when attempting to create the folder.

Note that company IT maps this folder to a network directory, this could be the root cause for the issue.

**Comment by sdottaka** [comment]
I don't know why it fails to create the WinMerge.txt file in the Documents/WinMerge folder, but I fixed it so that when it fails to create the file, it saves it in a temporary folder instead.
So I close this issue.
