### ISSUE TITLE
PgDn button auto-scrolls horizonal screen to "Home" position....

### ISSUE THREAD

**Issue by 4evermaat** [WinMerge/winmerge#900]
When I scroll right horizontally to look at some comparison, then scroll down vertically in order to look at more comparison from the same horizontal position.

If I scroll down  with the `Page Down` button, WinMerge horizontally resets to the line home position (far left of line).

If I scroll down with the scroll bar or the mouse wheel, then the horizontal position does not change.

edit:  if I move the mouse cursor into a nearby column, then use the page down button, the horizontal screen remains.

**Comment by sdottaka** [comment]
WinMerge is an editor rather than a viewer. Most editors will behave similarly to what you report when you press the PgUp, PgDn keys.

Scrolling with the scroll bar or mouse wheel does not change the caret position.
However, pressing the PgUp and PgDn keys will change the caret position. Horizontal scrolling can occur because the caret needs to be visible after the caret position has moved.
