### ISSUE TITLE
[Feature Request] Lengthen title of File Compare window or add tip

### ISSUE THREAD

**Issue by firstrose** [WinMerge/winmerge#960]
e.g C:\Project\1\index.htm and C:\Project\2\index.htm

They're all under control of SVN, and both are changed.

Now check change with winmerge.

Since File Compare window only shows bare filename, it's not easy to know the relationship of window and actual file.

![WinMergeU_Dj9Y8SF8YY](https://user-images.githubusercontent.com/1551595/132822598-582d68d4-38a6-4f0e-a55b-ea665eedc064.png)

**Comment by sdottaka** [comment]
The full path is now shown in the tooltip of the tab bar in commit 0e8066d.

![image](https://user-images.githubusercontent.com/98126/149642821-7a5d766b-9192-4c41-9d05-d6df92f98e75.png)

**Comment by mdell-seradex** [comment]
I know you have already closed this, but would it be better to use something like L:/M:/R:, for Left, Middle, Right, in the tooltip instead of 1:/2:/3:  Using the full word would make the alignment very inconsistent.
I ask because I wonder if people might not know which is "1" and which is "2", etc.  I was thinking this myself, looking at the tooltip.
An alternate would be to include the numbers in pane title bar.
I just thought I would mention this.

**Comment by sdottaka** [comment]
Thank you for the suggestion.
Since this tooltip is intended to supplement the omitted ones, I don't want to include L/M/R in the tooltip, which also needs to be supplemented.
I've added Left/Middle/Right to the end of the file name that appears in the tooltip in commit da4e39b.
